<?php
/**
 * Axonometric line drawing of the nursing home.
 *
 * GENERATED by tools/build-illustration.py — do not hand-edit. The geometry
 * is defined in 3D there and projected; that is the only way parallel edges
 * stay parallel and the window grids stay aligned on the receding face.
 * Run the script again to change the building.
 */

declare(strict_types=1);

function hospital_illustration(): string
{
    return <<<'SVG'
    <svg class="draw-art" viewBox="-8 98 634 308" width="560" height="272" role="img"
         aria-label="Axonometric line drawing of Sarada Nursing Home"
         fill="none" stroke="currentColor" stroke-width="2"
         stroke-linecap="round" stroke-linejoin="round">
      <path class="ln-ground g1" pathLength="1" d="M8.0 372.0 L592.0 372.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M20.0 372.0 L11.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M66.0 372.0 L57.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M112.0 372.0 L103.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M158.0 372.0 L149.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M204.0 372.0 L195.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M250.0 372.0 L241.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M296.0 372.0 L287.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M342.0 372.0 L333.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M388.0 372.0 L379.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M434.0 372.0 L425.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M480.0 372.0 L471.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M526.0 372.0 L517.0 380.0"/>
      <path class="ln-hatch g1" pathLength="1" d="M572.0 372.0 L563.0 380.0"/>
      <path class="ln-thin g1" pathLength="1" d="M59.7 359.5 L59.7 305.5"/>
      <path class="ln-thin g1" pathLength="1" d="M32.7 283.9a27 27 0 1 0 54 0a27 27 0 1 0 -54 0"/>
      <path class="ln-thin g1" pathLength="1" d="M591.0 364.5 L591.0 324.5"/>
      <path class="ln-thin g1" pathLength="1" d="M572.0 309.3a19 19 0 1 0 38 0a19 19 0 1 0 -38 0"/>
      <path class="ln-thin g1" pathLength="1" d="M73.7 375.0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"/>
      <path class="ln-thin g1" pathLength="1" d="M87.7 375.0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"/>
      <path class="f-top g2" pathLength="1" d="M92.0 196.0 L336.0 196.0 L386.2 167.0 L142.2 167.0Z"/>
      <path class="f-front g2" pathLength="1" d="M92.0 372.0 L336.0 372.0 L336.0 196.0 L92.0 196.0Z"/>
      <path class="f-top g2" pathLength="1" d="M336.0 156.0 L416.0 156.0 L466.2 127.0 L386.2 127.0Z"/>
      <path class="f-side g2" pathLength="1" d="M416.0 372.0 L466.2 343.0 L466.2 127.0 L416.0 156.0Z"/>
      <path class="f-front g2" pathLength="1" d="M336.0 372.0 L416.0 372.0 L416.0 156.0 L336.0 156.0Z"/>
      <path class="ln-thin g3" pathLength="1" d="M92.0 328.0 L336.0 328.0"/>
      <path class="ln-thin g3" pathLength="1" d="M92.0 284.0 L336.0 284.0"/>
      <path class="ln-thin g3" pathLength="1" d="M92.0 240.0 L336.0 240.0"/>
      <path class="ln-thin g3" pathLength="1" d="M336.0 328.0 L416.0 328.0"/>
      <path class="ln-thin g3" pathLength="1" d="M416.0 328.0 L466.2 299.0"/>
      <path class="ln-thin g3" pathLength="1" d="M336.0 284.0 L416.0 284.0"/>
      <path class="ln-thin g3" pathLength="1" d="M416.0 284.0 L466.2 255.0"/>
      <path class="ln-thin g3" pathLength="1" d="M336.0 240.0 L416.0 240.0"/>
      <path class="ln-thin g3" pathLength="1" d="M416.0 240.0 L466.2 211.0"/>
      <path class="ln-thin g3" pathLength="1" d="M336.0 196.0 L416.0 196.0"/>
      <path class="ln-thin g3" pathLength="1" d="M416.0 196.0 L466.2 167.0"/>
      <path class="f-top g3" pathLength="1" d="M83.4 185.5 L333.4 185.5 L388.8 153.5 L138.8 153.5Z"/>
      <path class="f-front g3" pathLength="1" d="M83.4 197.5 L333.4 197.5 L333.4 185.5 L83.4 185.5Z"/>
      <path class="ln-win g4" pathLength="1" d="M110.4 360.0 L148.4 360.0 L148.4 338.0 L110.4 338.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M129.4 360.0 L129.4 338.0"/>
      <path class="ln-win g4" pathLength="1" d="M166.8 360.0 L204.8 360.0 L204.8 338.0 L166.8 338.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M185.8 360.0 L185.8 338.0"/>
      <path class="ln-win g4" pathLength="1" d="M223.2 360.0 L261.2 360.0 L261.2 338.0 L223.2 338.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M242.2 360.0 L242.2 338.0"/>
      <path class="ln-win g4" pathLength="1" d="M279.6 360.0 L317.6 360.0 L317.6 338.0 L279.6 338.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M298.6 360.0 L298.6 338.0"/>
      <path class="ln-win g4" pathLength="1" d="M110.4 316.0 L148.4 316.0 L148.4 294.0 L110.4 294.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M129.4 316.0 L129.4 294.0"/>
      <path class="ln-win g4" pathLength="1" d="M166.8 316.0 L204.8 316.0 L204.8 294.0 L166.8 294.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M185.8 316.0 L185.8 294.0"/>
      <path class="ln-win-lit g4" pathLength="1" d="M223.2 316.0 L261.2 316.0 L261.2 294.0 L223.2 294.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M242.2 316.0 L242.2 294.0"/>
      <path class="ln-win g4" pathLength="1" d="M279.6 316.0 L317.6 316.0 L317.6 294.0 L279.6 294.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M298.6 316.0 L298.6 294.0"/>
      <path class="ln-win-lit g4" pathLength="1" d="M110.4 272.0 L148.4 272.0 L148.4 250.0 L110.4 250.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M129.4 272.0 L129.4 250.0"/>
      <path class="ln-win g4" pathLength="1" d="M166.8 272.0 L204.8 272.0 L204.8 250.0 L166.8 250.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M185.8 272.0 L185.8 250.0"/>
      <path class="ln-win g4" pathLength="1" d="M223.2 272.0 L261.2 272.0 L261.2 250.0 L223.2 250.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M242.2 272.0 L242.2 250.0"/>
      <path class="ln-win g4" pathLength="1" d="M279.6 272.0 L317.6 272.0 L317.6 250.0 L279.6 250.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M298.6 272.0 L298.6 250.0"/>
      <path class="ln-win g4" pathLength="1" d="M110.4 228.0 L148.4 228.0 L148.4 206.0 L110.4 206.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M129.4 228.0 L129.4 206.0"/>
      <path class="ln-win g4" pathLength="1" d="M166.8 228.0 L204.8 228.0 L204.8 206.0 L166.8 206.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M185.8 228.0 L185.8 206.0"/>
      <path class="ln-win g4" pathLength="1" d="M223.2 228.0 L261.2 228.0 L261.2 206.0 L223.2 206.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M242.2 228.0 L242.2 206.0"/>
      <path class="ln-win-lit g4" pathLength="1" d="M279.6 228.0 L317.6 228.0 L317.6 206.0 L279.6 206.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M298.6 228.0 L298.6 206.0"/>
      <path class="ln-win g4" pathLength="1" d="M345.3 362.0 L371.3 362.0 L371.3 338.0 L345.3 338.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M358.3 362.0 L358.3 338.0"/>
      <path class="ln-win g4" pathLength="1" d="M380.7 362.0 L406.7 362.0 L406.7 338.0 L380.7 338.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M393.7 362.0 L393.7 338.0"/>
      <path class="ln-win g4" pathLength="1" d="M424.1 357.3 L437.1 349.8 L437.1 325.8 L424.1 333.3Z"/>
      <path class="ln-win g4" pathLength="1" d="M445.2 345.2 L458.1 337.7 L458.1 313.7 L445.2 321.2Z"/>
      <path class="ln-win-lit g4" pathLength="1" d="M345.3 318.0 L371.3 318.0 L371.3 294.0 L345.3 294.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M358.3 318.0 L358.3 294.0"/>
      <path class="ln-win g4" pathLength="1" d="M380.7 318.0 L406.7 318.0 L406.7 294.0 L380.7 294.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M393.7 318.0 L393.7 294.0"/>
      <path class="ln-win g4" pathLength="1" d="M424.1 313.3 L437.1 305.8 L437.1 281.8 L424.1 289.3Z"/>
      <path class="ln-win g4" pathLength="1" d="M445.2 301.2 L458.1 293.7 L458.1 269.7 L445.2 277.2Z"/>
      <path class="ln-win g4" pathLength="1" d="M345.3 274.0 L371.3 274.0 L371.3 250.0 L345.3 250.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M358.3 274.0 L358.3 250.0"/>
      <path class="ln-win g4" pathLength="1" d="M380.7 274.0 L406.7 274.0 L406.7 250.0 L380.7 250.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M393.7 274.0 L393.7 250.0"/>
      <path class="ln-win g4" pathLength="1" d="M424.1 269.3 L437.1 261.8 L437.1 237.8 L424.1 245.3Z"/>
      <path class="ln-win g4" pathLength="1" d="M445.2 257.2 L458.1 249.7 L458.1 225.7 L445.2 233.2Z"/>
      <path class="ln-win g4" pathLength="1" d="M345.3 230.0 L371.3 230.0 L371.3 206.0 L345.3 206.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M358.3 230.0 L358.3 206.0"/>
      <path class="ln-win g4" pathLength="1" d="M380.7 230.0 L406.7 230.0 L406.7 206.0 L380.7 206.0Z"/>
      <path class="ln-thin g4" pathLength="1" d="M393.7 230.0 L393.7 206.0"/>
      <path class="ln-win g4" pathLength="1" d="M424.1 225.3 L437.1 217.8 L437.1 193.8 L424.1 201.3Z"/>
      <path class="ln-win g4" pathLength="1" d="M445.2 213.2 L458.1 205.7 L458.1 181.7 L445.2 189.2Z"/>
      <path class="f-top g5" pathLength="1" d="M333.4 145.5 L421.4 145.5 L476.8 113.5 L388.8 113.5Z"/>
      <path class="f-side g5" pathLength="1" d="M421.4 157.5 L476.8 125.5 L476.8 113.5 L421.4 145.5Z"/>
      <path class="f-front g5" pathLength="1" d="M333.4 157.5 L421.4 157.5 L421.4 145.5 L333.4 145.5Z"/>
      <path class="ln-mark g5" pathLength="1" d="M373.4 151.5 L373.4 142.5"/>
      <path class="ln-mark g5" pathLength="1" d="M368.9 147.0 L377.9 147.0"/>
      <path class="ln-win g5" pathLength="1" d="M148.0 372.0 L204.0 372.0 L204.0 338.0 L148.0 338.0Z"/>
      <path class="ln-thin g5" pathLength="1" d="M176.0 372.0 L176.0 338.0"/>
      <path class="f-top g5" pathLength="1" d="M94.6 334.5 L202.6 334.5 L226.0 321.0 L118.0 321.0Z"/>
      <path class="f-side g5" pathLength="1" d="M202.6 345.5 L226.0 332.0 L226.0 321.0 L202.6 334.5Z"/>
      <path class="f-front g5" pathLength="1" d="M94.6 345.5 L202.6 345.5 L202.6 334.5 L94.6 334.5Z"/>
      <path class="ln-thin g5" pathLength="1" d="M101.6 385.5 L101.6 345.5"/>
      <path class="ln-thin g5" pathLength="1" d="M195.6 385.5 L195.6 345.5"/>
      <path class="ln-win g5" pathLength="1" d="M118.6 344.0 L178.6 344.0 L178.6 336.0 L118.6 336.0Z"/>
      <path class="ln-thin g5" pathLength="1" d="M125.6 340.0 L171.6 340.0"/>
      <path class="f-front g5" pathLength="1" d="M78.6 389.0 L206.6 389.0 L212.6 385.5 L84.6 385.5Z"/>
      <path class="ln-hatch g6" pathLength="1" d="M409.2 384.0 L545.2 384.0"/>
      <path class="f-top g6" pathLength="1" d="M438.5 345.5 L500.5 345.5 L513.5 338.0 L451.5 338.0Z"/>
      <path class="f-side g6" pathLength="1" d="M500.5 377.5 L513.5 370.0 L513.5 338.0 L500.5 345.5Z"/>
      <path class="f-front g6" pathLength="1" d="M438.5 377.5 L500.5 377.5 L500.5 345.5 L438.5 345.5Z"/>
      <path class="f-side g6" pathLength="1" d="M528.5 377.5 L541.5 370.0 L541.5 346.0 L528.5 353.5Z"/>
      <path class="f-front g6" pathLength="1" d="M500.5 377.5 L528.5 377.5 L528.5 353.5 L500.5 353.5Z"/>
      <path class="f-top g6" pathLength="1" d="M500.5 353.5 L528.5 353.5 L541.5 346.0 L513.5 346.0Z"/>
      <path class="ln-thin g6" pathLength="1" d="M500.5 377.5 L500.5 353.5"/>
      <path class="ln-win g6" pathLength="1" d="M505.5 364.5 L523.5 364.5 L523.5 356.5 L505.5 356.5Z"/>
      <path class="ln-win g6" pathLength="1" d="M476.5 361.5 L494.5 361.5 L494.5 350.5 L476.5 350.5Z"/>
      <path class="ln-thin g6" pathLength="1" d="M444.5 372.0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"/>
      <path class="ln-thin g6" pathLength="1" d="M449.0 372.0a2.5 2.5 0 1 0 5.0 0a2.5 2.5 0 1 0 -5.0 0"/>
      <path class="ln-thin g6" pathLength="1" d="M507.5 372.0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"/>
      <path class="ln-thin g6" pathLength="1" d="M512.0 372.0a2.5 2.5 0 1 0 5.0 0a2.5 2.5 0 1 0 -5.0 0"/>
      <path class="ln-mark g6" pathLength="1" d="M460.5 362.5 L460.5 352.5"/>
      <path class="ln-mark g6" pathLength="1" d="M455.5 357.5 L465.5 357.5"/>
      <path class="ln-mark g6" pathLength="1" d="M462.8 343.0 L478.8 343.0 L478.8 339.0 L462.8 339.0Z"/>
      <path class="ln-thin g6" pathLength="1" d="M207.84 365.2a4.16 4.16 0 1 0 8.32 0a4.16 4.16 0 1 0 -8.32 0"/>
      <path class="ln-thin g6" pathLength="1" d="M212.0 370.2 L212.0 375.3"/>
      <path class="ln-thin g6" pathLength="1" d="M212.0 375.3 L208.0 387.0"/>
      <path class="ln-thin g6" pathLength="1" d="M212.0 375.3 L216.0 387.0"/>
      <path class="ln-thin g6" pathLength="1" d="M230.62 368.7a3.68 3.68 0 1 0 7.36 0a3.68 3.68 0 1 0 -7.36 0"/>
      <path class="ln-thin g6" pathLength="1" d="M234.3 373.1 L234.3 377.6"/>
      <path class="ln-thin g6" pathLength="1" d="M234.3 377.6 L230.3 388.0"/>
      <path class="ln-thin g6" pathLength="1" d="M234.3 377.6 L238.3 388.0"/>
    </svg>
    SVG;
}
